### ISSUE TITLE
News Article Format

### ISSUE THREAD

**Issue by haydenrust1** [clydeclark/covidTracking#43]
The news article headlines need bolding to differentiate between the heading and the body of the news article.  I suggest we also shorten the amount of the body that gets displayed, almost like a teaser/ snippet of what you would be reading.

**Comment by clydeclark** [comment]
The bolding part is easy.  Keep in mind, what is being displayed is a summary so we need to make sure the link to the actual article remains.

**Comment by haydenrust1** [comment]
Hayden, Mason, and Clyde formatted news articles
